export const globalConstants = {
  // GET_TRAININGS_IN_PROCESS: 'GET_TRAININGS_IN_PROCESS',
  // GET_TRAININGS_SUCCESS: 'GET_TRAININGS_SUCCESS',
  // GET_TRAININGS_FAILURE: 'GET_TRAININGS_FAILURE',

  GET_TRAINING_IN_PROCESS: 'GET_TRAINING_IN_PROCESS',
  GET_TRAINING_SUCCESS: 'GET_TRAINING_SUCCESS',
  GET_TRAINING_FAILURE: 'GET_TRAINING_FAILURE',

  REMOVE_TRAINING_IN_PROCESS: 'REMOVE_TRAINING_IN_PROCESS',
  REMOVE_TRAINING_SUCCESS: 'REMOVE_TRAINING_SUCCESS',
  REMOVE_TRAINING_FAILURE: 'REMOVE_TRAINING_FAILURE',

  // GET_USERS_IN_PROCESS: 'GET_USERS_IN_PROCESS',
  // GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  // GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  GET_USER_IN_PROCESS: 'GET_USER_IN_PROCESS',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  REMOVE_USER_IN_PROCESS: 'REMOVE_USER_IN_PROCESS',
  REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
  REMOVE_USER_FAILURE: 'REMOVE_USER_FAILURE',

  // GET_TRAINING_CATEGORIES_IN_PROCESS: 'GET_TRAINING_CATEGORIES_IN_PROCESS',
  // GET_TRAINING_CATEGORIES_SUCCESS: 'GET_TRAINING_CATEGORIES_SUCCESS',
  // GET_TRAINING_CATEGORIES_FAILURE: 'GET_TRAINING_CATEGORIES_FAILURE',

  GET_TRAINING_CATEGORY_IN_PROCESS: 'GET_TRAINING_CATEGORY_IN_PROCESS',
  GET_TRAINING_CATEGORY_SUCCESS: 'GET_TRAINING_CATEGORY_SUCCESS',
  GET_TRAINING_CATEGORY_FAILURE: 'GET_TRAINING_CATEGORY_FAILURE',

  ADD_TRAINING_CATEGORY_IN_PROCESS: 'ADD_TRAINING_CATEGORY_IN_PROCESS',
  ADD_TRAINING_CATEGORY_SUCCESS: 'ADD_TRAINING_CATEGORY_SUCCESS',
  ADD_TRAINING_CATEGORY_FAILURE: 'ADD_TRAINING_CATEGORY_FAILURE',

  EDIT_TRAINING_CATEGORY_IN_PROCESS: 'EDIT_TRAINING_CATEGORY_IN_PROCESS',
  EDIT_TRAINING_CATEGORY_SUCCESS: 'EDIT_TRAINING_CATEGORY_SUCCESS',
  EDIT_TRAINING_CATEGORY_FAILURE: 'EDIT_TRAINING_CATEGORY_FAILURE',

  REMOVE_TRAINING_CATEGORY_IN_PROCESS: 'REMOVE_TRAINING_CATEGORY_IN_PROCESS',
  REMOVE_TRAINING_CATEGORY_SUCCESS: 'REMOVE_TRAINING_CATEGORY_SUCCESS',
  REMOVE_TRAINING_CATEGORY_FAILURE: 'REMOVE_TRAINING_CATEGORY_FAILURE',

  // GET_EXERCISE_CATEGORIES_IN_PROCESS: 'GET_EXERCISE_CATEGORIES_IN_PROCESS',
  // GET_EXERCISE_CATEGORIES_SUCCESS: 'GET_EXERCISE_CATEGORIES_SUCCESS',
  // GET_EXERCISE_CATEGORIES_FAILURE: 'GET_EXERCISE_CATEGORIES_FAILURE',

  GET_EXERCISE_CATEGORY_IN_PROCESS: 'GET_EXERCISE_CATEGORY_IN_PROCESS',
  GET_EXERCISE_CATEGORY_SUCCESS: 'GET_EXERCISE_CATEGORY_SUCCESS',
  GET_EXERCISE_CATEGORY_FAILURE: 'GET_EXERCISE_CATEGORY_FAILURE',

  // ADD_EXERCISE_CATEGORY_IN_PROCESS: 'ADD_EXERCISE_CATEGORY_IN_PROCESS',
  // ADD_EXERCISE_CATEGORY_SUCCESS: 'ADD_EXERCISE_CATEGORY_SUCCESS',
  // ADD_EXERCISE_CATEGORY_FAILURE: 'ADD_EXERCISE_CATEGORY_FAILURE',

  EDIT_EXERCISE_CATEGORY_IN_PROCESS: 'EDIT_EXERCISE_CATEGORY_IN_PROCESS',
  EDIT_EXERCISE_CATEGORY_SUCCESS: 'EDIT_EXERCISE_CATEGORY_SUCCESS',
  EDIT_EXERCISE_CATEGORY_FAILURE: 'EDIT_EXERCISE_CATEGORY_FAILURE',

  REMOVE_EXERCISE_CATEGORY_IN_PROCESS: 'REMOVE_EXERCISE_CATEGORY_IN_PROCESS',
  REMOVE_EXERCISE_CATEGORY_SUCCESS: 'REMOVE_EXERCISE_CATEGORY_SUCCESS',
  REMOVE_EXERCISE_CATEGORY_FAILURE: 'REMOVE_EXERCISE_CATEGORY_FAILURE',

  // GET_CONTACT_MESSAGES_IN_PROCESS: 'GET_CONTACT_MESSAGES_IN_PROCESS',
  // GET_CONTACT_MESSAGES_SUCCESS: 'GET_CONTACT_MESSAGES_SUCCESS',
  // GET_CONTACT_MESSAGES_FAILURE: 'GET_CONTACT_MESSAGES_FAILURE',

  GET_CONTACT_MESSAGE_IN_PROCESS: 'GET_CONTACT_MESSAGE_IN_PROCESS',
  GET_CONTACT_MESSAGE_SUCCESS: 'GET_CONTACT_MESSAGE_SUCCESS',
  GET_CONTACT_MESSAGE_FAILURE: 'GET_CONTACT_MESSAGE_FAILURE',

  REMOVE_CONTACT_MESSAGE_IN_PROCESS: 'REMOVE_CONTACT_MESSAGE_IN_PROCESS',
  REMOVE_CONTACT_MESSAGE_SUCCESS: 'REMOVE_CONTACT_MESSAGE_SUCCESS',
  REMOVE_CONTACT_MESSAGE_FAILURE: 'REMOVE_CONTACT_MESSAGE_FAILURE',

  // GET_TOKENS_IN_PROCESS: 'GET_TOKENS_IN_PROCESS',
  // GET_TOKENS_SUCCESS: 'GET_TOKENS_SUCCESS',
  // GET_TOKENS_FAILURE: 'GET_TOKENS_FAILURE',

  REMOVE_TOKEN_IN_PROCESS: 'REMOVE_TOKEN_IN_PROCESS',
  REMOVE_TOKEN_SUCCESS: 'REMOVE_TOKEN_SUCCESS',
  REMOVE_TOKEN_FAILURE: 'REMOVE_TOKEN_FAILURE',
}
