export const authConstants = {
  LOGIN_IN_PROCESS: 'LOGIN_IN_PROCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REFRESH_TOKEN_IN_PROCESS: 'REFRESH_TOKEN_IN_PROCESS',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

  LOGOUT_IN_PROGRESS: 'LOGOUT_IN_PROGRESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  SAVE_ACCESS_TOKEN_SUCCESS: 'SAVE_ACCESS_TOKEN_SUCCESS',

  CHANGE_PASSWORD_IN_PROCESS: 'CHANGE_PASSWORD_IN_PROCESS',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
}
